### ISSUE TITLE
Server crashing when I type .mimic/.replays

### ISSUE THREAD

**Issue by Chaazz22** [CHR15cs/CS2-Practice-Plugin#65]
Hi, Im not an IT guy just a dude that follow tutorial lol. So my dedicated server is crashing whenever Im typing .replays or .mimic. I get this error on the console server, do you have any sugestion ? I used the metamod dev build 1266 and the 1282 it does the same thing. 
The message :

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at CounterStrikeSharp.API.Core.Helpers.InvokeNative(IntPtr)
--------------------------------
   at CounterStrikeSharp.API.Core.ScriptContext.InvokeNativeInternal()
   at CounterStrikeSharp.API.Core.ScriptContext.Invoke()
   at CounterStrikeSharp.API.Core.NativeAPI.FireEventToClient(IntPtr, Int32)
   at CounterStrikeSharp.API.Modules.Events.GameEvent.FireEventToClient(CounterStrikeSharp.API.Core.CCSPlayerController)
   at CounterStrikeSharp.API.Core.CCSPlayerController.PrintToCenterHtml(System.String, Int32)
   at CSPracc.Managers.GuiManager.OnTick()
   at DynamicClass.InvokeStub_OnTick.Invoke(System.Object, System.Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at CounterStrikeSharp.API.Core.BasePlugin+<>c__DisplayClass45_0`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=*****************]].<RegisterListener>b__2(CounterStrikeSharp.API.Core.ScriptContext)
   at DynamicClass.InvokeStub_Action`1.Invoke(System.Object, System.Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(System.Object, IntPtr*, System.Reflection.BindingFlags)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at CounterStrikeSharp.API.Core.FunctionReference+<>c__DisplayClass3_0.<.ctor>b__0(CounterStrikeSharp.API.Core.fxScriptContext*)

**Comment by CHR15cs** [comment]
I will try to reproduce this

**Comment by CHR15cs** [comment]
Which css version are you using?
