### ISSUE TITLE
Crashing whenever using .nades or .replays

### ISSUE THREAD

**Issue by villeeh** [CHR15cs/CS2-Practice-Plugin#70]
Whenever i try and use .nades or .replays etc server crashes with this error code:
` ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadByte(IntPtr ptr, Int32 ofs)
   at CounterStrikeSharp.API.Core.ScriptContext.GetResult(Type type, Byte* ptr) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 451
   at CounterStrikeSharp.API.Core.NativeAPI.GetSchemaValueByName[T](IntPtr instance, Int32 returntype, String classname, String propname) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1101
   at CounterStrikeSharp.API.Core.CBasePlayerController.get_PlayerName() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Objects.g.cs:line 5103
   at CSPracc.EventHandler.PracticeEventHandler.OnPlayerHurt(EventPlayerHurt event, GameEventInfo info) in D:\Development\repos\CS2 Practice Plugin\CS2-Practice-Plugin\CSPracc\Modes\PracticeMode\PracticeEventHandler.cs:line 63
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---`

**Comment by CHR15cs** [comment]
Update to this CSS Version 
https://github.com/roflmuffin/CounterStrikeSharp/releases/tag/v198
